name = "spicyshowchat"
main = "worker.js"
compatibility_date = "2024-07-01"

# Durable Object 配置
[[durable_objects]]
name = "CHATROOM"
class_name = "ChatRoomDurableObject"

[durable_objects.bindings]
CHATROOM = "spicyshowchat_ChatRoomDurableObject"

# Durable Object 存储迁移（如用 SQL 存储，推荐用 new_sqlite_classes）
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoomDurableObject"]

# 路由
# 如果你已绑定自定义域名，按需修改此项
# routes = [ "https://你的域名.com/room/*" ]

# 变量和 secrets 可选
# [vars]
# SOME_KEY = "your-value"

# 其他配置见官方文档
