name = "cloudflare-do-chat"
main = "worker.js"
compatibility_date = "2024-07-01"

[[durable_objects]]
name = "CHATROOM"
class_name = "ChatRoom"

[durable_objects.bindings]
CHATROOM = "cloudflare-do-chat_ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]
