name = "durable-object-chat"
main = "worker.js"
compatibility_date = "2024-07-01"

[[durable_objects]]
binding = "CHATROOM"
class_name = "ChatRoomDurableObject"

[vars]
# 你可以在这里定义环境变量

[triggers]
# 可选，自动部署等
