name = "cloudflare-do-chat"
main = "worker.js"
compatibility_date = "2024-07-01"

[durable_objects]
bindings = [
  { name = "CHATROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]
